### ISSUE TITLE
Use a virtual file system

### ISSUE THREAD

**Issue by pvdlg** [davidtheclark/cosmiconfig#105] opened 2018-02-01 06:03 UTC
On a [GitHub app](https://developer.github.com/apps) the file system and the cloned repo are not available. Currently `cosmiconfig` browse the filesystem to find the config files, so it cannot be used with a GitHub app.

Would it be possible to pass to the `load` function a `Array` of file `Objects`, which would contains the the file path and the file content as a `String` or a `Buffer`?
So a GitHub app could retrieve the config files as a `String` or `Buffer` and pass them to `cosmiconfig`.

For example:
```js
const explorer = cosmiconfig('mymodule', [
  {path: 'mymodulerc.yml', content: '....'},
  {path: 'dir/mymodulerc.yml', content: '....'},
]);

explorer.load();
// => use config from `mymodulerc.yml`

explorer.load('dir');
// => use config from `dir/mymodulerc.yml`

explorer.load(null, 'dir/mymodulerc.yml');
// => use config from `dir/mymodulerc.yml`
```

**Comment by davidtheclark** [comment] 2018-02-01 19:08
Hi @pvdlg. To make sure I understand the full situation: What is the benefit of using cosmiconfig in your situation? Is it only to handle file format flexibility (i.e. your config might be YAML, JSON, or JS)? If so, maybe it would make sense to expose the parsing method that makes these parsing attempts (see [`loadDefinedFile`](https://github.com/davidtheclark/cosmiconfig/blob/e520cde1cbbbd528e8b0533c3f02bcb35e8a359e/src/loadDefinedFile.js).

**Comment by pvdlg** [comment] 2018-02-01 19:55
The benefit would be to able to use cosmiconfig in a project, for both CLI and GitHub app usage.

In the case of a GitHub app cosmiconfig could bring the following advantages:
- Parse any compatible file independently of the format
- Find the config file the closest to the file passed in the `load` function

I'm not sure exposing `loadDefinedFile` as is would work as the function seems to read the file on the disk. It would also be beneficial to use the cache, determine the file format based on it's name and content and finding the config file the closest to file passed in `load`.

**Comment by davidtheclark** [comment] 2018-02-01 20:00
> Find the config file the closest to the file passed in the load function

Find the file based on a virtual filesystem object that you pass in? So it would actually try to consolidate `path` properties of these objects into a mock filesystem and traverse that?

**Comment by pvdlg** [comment] 2018-02-01 20:06
> Find the file based on a virtual filesystem object that you pass in? So it would actually try to consolidate path properties of these objects into a mock filesystem and traverse that?

Yes. It's just a proposal. I don't know how hard it would be to implement and if the benefits would justify the effort though.

**Comment by davidtheclark** [comment] 2018-02-03 23:16
I see ... 

I think that the intention here (taking a module that expects a real file system and running it within a virtual one) is not specific to cosmiconfig, so any solution to it shouldn't be specific to cosmiconfig, either. If there were some generic method for accomplishing this, we could look into how to make that work with cosmiconfig. There may be! But I guess I don't think that cosmiconfig should implement its own specific solution.

**Comment by sudo-suhas** [comment] 2018-02-05 02:50
@davidtheclark [`memory-fs`](https://github.com/webpack/memory-fs) could be used for this. We would have to accept `fs` as a parameter with the default as `require('fs')`. Right now, in our source code, we only access `fs` from `readFile.js`. However, we might need to implement [`is-directory`](https://github.com/jonschlinkert/is-directory) ourselves to be able to pass the filesystem instance.

**Comment by davidtheclark** [comment] 2018-02-07 15:51
@sudo-suhas: Sure, but even with that tool we'd need to change cosmiconfig to accommodate, which I feel weird about given how generic the problem is. Doesn't seem like a responsibility this library should have to take on — especially if it's not something that all kinds of other fs-reading libraries are doing. (Or *are* they doing it?)

**Comment by sudo-suhas** [comment] 2018-02-12 03:26
The only other way I can think of is to mock the `fs` library and substitute `memory-fs` using something like [`mockery`](https://www.npmjs.com/package/mockery). This could be packaged into a separate wrapper library.

**Comment by davidtheclark** [comment] 2018-02-17 19:27
@sudo-suhas that's a good idea to try: use a mocking library to hijack `fs` *in the code of your GitHub app* — that would mean that all the libraries you use would not have to make special accommodations for the possibility of a virtual file system.

@pvdlg I'd love to hear if that works for you. I'm going to close this issue for now, because I'm still of the opinion that the problem is too generic for cosmiconfig. Still open to hearing others' thoughts and ideas, though.

**Comment by pvdlg** [comment] 2018-02-18 02:50
Mocking the `fs` functions seems way too hacky...

For an application that runs both on the files system (as a CLI tool) and in a GitHub app (via API) it would really difficult to use `cosmiconfig` unfortunately, as the `cosmiconfig` features to parse any compatible file independently of the format and to find the closest config file would have to be reimplemented in the GitHub app.

Having two different implementation (one in `cosmiconfig` and a custom one in the app) is not really convenient and can create discrepancies. 

Maybe `cosmiconfig` could expose the following?
- a function to get all the valid filenames to look for
- a function that detect the format and parse the config file

**Comment by davidtheclark** [comment] 2018-02-18 22:35
@pvdlg I'm still wondering if there is any precedent for addressing this problem outside of cosmiconfig. I can't imagine this problem is specific to cosmiconfig, right?

**Comment by pvdlg** [comment] 2018-02-18 23:09
I guess usually project allow only one type of configuration (either yaml or json).
As `cosmiconfig` introduced the possibility to have multiple format that can be handled automatically, the problem arise for code that can run both with and without the cloned repo.

In such situation the code in `src/loadRc.js` would have to be duplicated in the case of a GitHub app.

**Comment by pvdlg** [comment] 2018-03-16 01:57
Would it be possible to expose the [parseContent](https://github.com/davidtheclark/cosmiconfig/blob/debda6788340aca9c13d5bfdd10f0622dbe3fef7/src/loadDefinedFile.js#L17) function by chance?

That would allow a GitApp to figure out by itself the config file to use and parse it with `parseContent` which can recognize the different supported format (json, js, yaml). That would cover most of the requirement for such situation.

**Comment by olsonpm** [comment] 2018-03-16 03:08
I was interested in what mocking the fs module would feel like - it's actually not too bad.  I'd also imagine populating a javascript object with your virtual file system wouldn't be difficult.

```js
const { vol } = require('memfs'),
  mockery = require('mockery');

mockery.enable();
mockery.warnOnUnregistered(false);

const volume = {
  'test-cosmiconfig/child/test.js': '{ "foundme": "true" }',
  'test-cosmiconfig/.prettierrc': '{ "foundme": "true" }'
};

vol.fromJSON(volume, '/');
mockery.registerMock('fs', vol);
const createExplorer = require('cosmiconfig');
const explorer = createExplorer('prettier');

explorer
  .load(null, '/test-cosmiconfig/.somemodulerc')
  .then(loadResult => console.log(loadResult))
  .catch(anError => console.error(anError));

// outputs
// { config: { foundme: 'true' },
//   filepath: '/test-cosmiconfig/.somemodulerc' }
```

**Comment by pvdlg** [comment] 2018-03-16 03:15
In the context of a GitHub app, mocking the file system might not be an option, as the mock will be global. The application wouldn't be able access the real FS, not even for logging.

Even in an other context, using a mock library made for testing might create a lot of unintended effects....

In this use case, I'd rather write the code to find the correct config file and parse it with `parseContent`....

**Comment by olsonpm** [comment] 2018-03-16 03:24
yeah I guess my vote would be to add an 'fs' option where people can pass their own file system object.  This is how I've seen this problem solved anyway.  By default we would just use the required fs, but people can provide a memfs such as above if they choose.

I'm not fond of exposing an internal function - I like the simplicity and focus of the API as it stands now.

**Comment by pvdlg** [comment] 2018-03-16 03:33
Yes that would be ideal, but as this issue was closed I don't think it would be implemented...

Exposing `parseContent` would be fairly simple and would solve a big part of the problem, which is why I proposed this solution.

It could even be extracted to a separate npm module. The functionality of parsing a file content (or even a string) that could be either json, js or yaml would be quite useful even outside of cosmiconfig.

In the use case of a project working both as a CLI or within a GitHub app, the important thing is for the parsing to be the identical in both scenario to avoid bugs and discrepancy. So exposing the parsing function via API or via an npm module would solve that problem.

**Comment by sudo-suhas** [comment] 2018-03-17 05:37
@davidtheclark Would you reconsider accepting `fs` as an optional parameter to `createExplorer`?

**Comment by davidtheclark** [comment] 2018-03-17 14:44
🤷‍♂️ I guess if everybody else thinks this seems like a good idea, I'm open to looking at a more precise outline of what feature would mean (what exactly would the user provide, how exactly would cosmiconfig use it, etc.). Would the user pass in some complete fake `fs` like [memfs](https://github.com/streamich/memfs) or [avfs](https://www.npmjs.com/package/avfs)? 

> This is how I've seen the problem solved anyway.

@olsonpm where have you seen this problem solved before? As I've expressed above, I'd love to see precedent.

**Comment by olsonpm** [comment] 2018-03-17 14:49
sure i'm pretty sure it was webpack related e.g. regular fs for writing output to the file system for creating a deployment and memfs for hotreload local development.  I'll find code to reference though to make sure i'm not misremembering

**Comment by olsonpm** [comment] 2018-03-19 16:29
Finally at my computer today.  Webpack does allow users to modify the "outputFileSystem"

documentation:
https://webpack.js.org/api/node/#custom-file-systems

[example usage with ssr and vue](https://github.com/vuejs/vue-hackernews-2.0/blob/master/build/setup-dev-server.js#L73)

**Comment by davidtheclark** [comment] 2018-03-24 16:48
Here are the steps I see to allowing the user to pass in a custom `fs` module:

- Implement our own `isDirectory` function, instead of using the `is-directory` module.
- Document precisely which `fs` methods we use. That way we can document that the user-provided `fs` *must* expose those methods.
- Try it out, maybe with `memfs`.

Does that sound right?

**Comment by olsonpm** [comment] 2018-03-24 16:58
sounds good to me

**Comment by sudo-suhas** [comment] 2018-03-31 10:08
reopening. @davidtheclark Would we want to target this in v5 release? Personally, I think we could but not needed since this won't break backward compatibility. So we can pick this up after v5 release.

**Comment by davidtheclark** [comment] 2018-03-31 17:49
@sudo-suhas Agreed. It could go into whatever release it's ready for.

**Comment by sudo-suhas** [comment] 2018-05-15 03:41
@pvdlg Are you still interested in this functionality? If so, I can work on a PR which implements the changes outlined in https://github.com/davidtheclark/cosmiconfig/issues/105#issuecomment-375907150.

**Comment by pvdlg** [comment] 2018-05-15 08:13
Yes I would still be interested in such feature! Thanks!

**Comment by sudo-suhas** [comment] 2018-05-16 05:33
Please see #143 and let me know what you think.

**Comment by davidtheclark** [comment] 2021-02-14 00:10
Closing as stale, since there's been no additional interest here.

**Closed by davidtheclark** 2021-02-14 00:10 UTC
