### ISSUE TITLE
Would you take a PR to throw an error for all empty configs?

### ISSUE THREAD

**Issue by olsonpm** [davidtheclark/cosmiconfig#106] opened 2018-02-04 19:45 UTC
Current behavior:  

When using `load(null, configPath)` [cosmiconfig throws an error](https://github.com/davidtheclark/cosmiconfig/blob/master/src/loadDefinedFile.js#L18-L20)

When using `load(dirPath)` [cosmiconfig continues to traverse up the directory path](https://github.com/davidtheclark/cosmiconfig/blob/master/src/loadRc.js#L35)

If this was intentional then please help me understand why.  Otherwise I would like to create a PR to throw in all cases.  I don't really care whether an error is thrown, ~~we're mostly looking for a way to differentiate empty configurations from those which are non-existent.  e.g. `package.json` with an empty `prettier` property should behave differently from a package.json without a `prettier` property.~~

Edit: I was basing the above off of issue comments I was reading in the prettier repo - not off of local tests.  When cosmiconfig sees a package.json file with `"prettier": {}`, it correctly returns an empty object and does not traverse up the file tree.  However it still treats an empty *rc file as non-existent.  I now understand this is an edge case that really can really only help expose configuration errors made by developers.
<br>

#### Why
`prettier-atom` would like to allow users to specify settings within the plugin for one-off cases where files do not belong to projects.  However if **any configuration is found, even empty** then we would like to use that configuration instead.  Empty signifying default settings.

**Comment by sudo-suhas** [comment] 2018-02-05 03:23
@olsonpm, When loading a specified file, the behavior was inconsistent if the file was empty(see https://github.com/davidtheclark/cosmiconfig/pull/78#issuecomment-318810892) and this was fixed in `v3.0.0`. However, when performing a search up the directory tree, I am not entirely sure that we should throw an error when we find an empty config file. 

> `package.json` with an empty prettier property should behave differently from a `package.json` without a prettier property.

If the pkg has an empty property, the search resolves with `{}`. The same is true for a JSON file with `{}` as the contents. So would it be enough to check if the value that `cosmiconfig` search resolves to, is an empty object?

<details>
<summary>resolve to empty cfg</summary>

**`package.json`:**

```json
{
  "name": "prettier-pkg-empty-cfg",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "prettier": "^1.10.2"
  },
  "prettier": {}
}
```

```
λ node
> let prettier = require('prettier')
> let filepath = path.resolve('./index.js')
'E:\\Projects\\experiments\\prettier-pkg-empty-cfg\\index.js'
> prettier.resolveConfig(filepath).then(console.log);
> {}
```

</details>

**Comment by davidtheclark** [comment] 2018-02-07 15:45
> If this was intentional then please help me understand why.

I'll try to explain the original intention. 

`load(null, configPath)` is supposed to point at a particular file. If you use that argument, your suggesting "A config file *should* be here." In that case, if there's no config file there, there's been a misunderstanding and you'll want an error — same as if you told `fs.readFile` to read a file that doesn't exist.

`load(dirPath)` is supposed to *search*, starting in that directory, for a config. If nothing is found, that's not really an error — it's just that nothing was found.

(Make sense? Or is that silly?)

If I understand correctly, the problem is that an empty (but existent) config is treated the same as a non-existent config when you're searching. I think I agree with @olsonpm that if an empty config is found, cosmiconfig should *not* continue searching, but should return with the filepath to the empty config and either `{}` or `undefined` or `null` for the config. The fact that you got this object, and it has a `filepath` property, would then be enough to distinguish between an empty config and no config. 

What do you think?

**Comment by davidtheclark** [comment] 2018-02-07 15:48
This also reminds me that I don't really like this overloading of `load`. It would be preferable to have two functions, right? Maybe `load` (specified file) and `search` (from a directory)?

Maybe if we need to introduce another breaking change, we should also make that change, to clarify things. Unless people disagree.

**Comment by olsonpm** [comment] 2018-02-07 21:30
Thanks so much for your feedback

> So would it be enough to check if the value that cosmiconfig search resolves to, is an empty object?
Yes - and I'm sorry for the incorrect example as I really should have tested that.  However, isn't an *rc file with `{}` to json equivalent to an empty file for yaml?

> if an empty config is found, cosmiconfig should not continue searching, but should return with the filepath to the empty config and either {} or undefined or null for the config.
Agreed - though I still think an empty *rc file should be parsed as yaml and thus be treated as an empty config `{}`.  I don't use yaml though so I could be missing something.

> It would be preferable to have two functions, right?
Agreed 👍

**Comment by davidtheclark** [comment] 2018-03-25 15:28
Empty configs are now handled consistently in the v5 branch, so closing this issue.

**Closed by davidtheclark** 2018-03-25 15:28 UTC
