### ISSUE TITLE
Support `[.]*rc.js` files

### ISSUE THREAD

**Issue by adjohnson916** [davidtheclark/cosmiconfig#58] opened 2017-03-23 16:12 UTC
Support `[.]*rc.js` files, like `.eslintrc.js`, with optional dot prefix like #57.

**Comment by davidtheclark** [comment] 2017-03-25 01:48
This can already be done with the `rc` option, right?

**Comment by adjohnson916** [comment] 2017-03-25 02:15
@davidtheclark Not sure, maybe with `rcExtensions: true`, but not sure if that can be done for both hidden and not hidden files since there's only one `rc` template?

**Comment by davidtheclark** [comment] 2017-03-25 16:18
Closing as duplicate of #57. Let's discuss over there, as I think it's pretty much the same question.

**Closed by davidtheclark** 2017-03-25 16:18 UTC
